name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container:
      image: ragnaroek/rust-raspberry:1.67.0
      options: --user root
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: build --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: spotify-player
        path: target/release/spotify-player
