name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container: ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        apt install librust-alsa-sys-dev
        cargo build --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: spotify-player
        path: target/release/spotify-player
