name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container: ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: armv7-unknown-linux-gnueabihf
        override: true

    - name: Build
      run: |
        apt-get update
        apt-get install ---yes libasound2-dev pkg-config
        export PKG_CONFIG_SYSROOT_DIR=/

    - uses: actions-rs/cargo@v1
      with:
        use-cross: false
        command: build
        args: --target armv7-unknown-linux-gnueabihf

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: spotify-player
        path: target/release/spotify-player
